config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(flat_params)

    redirect_to @flat
  end

  def destroy
    @flat.destroy

    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(@flat) do |f| %>
    <div class="container">
      <div class="row justify-content-center">
        <div class="py-2 col-12 col-sm-4">
          <form>
            <h2 class="text-center mb-5">Create / Edit !</h2>
            <div class="form-row">
              <div class="name">  <%= f.label :name %></div>
              <%= f.text_field :name %>
              <%= f.label :address %>
              <%= f.text_field :address %>
              <%= f.label :description %>
              <%= f.text_field :description %>
              <%= f.label :price_per_night %>
              <%= f.text_field :price_per_night %>
              <%= f.label :number_of_guests %>
              <%= f.text_field :number_of_guests %>
              <%= f.submit %>
              <div class="col-6 form-group">
                <label for="exampleFormControlInput1"></label>
              </div>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1"></label>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1"></label>
            </div>
          </form>
        </div>
      </div>
    </div>
<% end %>

app/views/flats/edit.html.erb
<%= render 'form', article: @article %>

app/views/flats/index.html.erb
<nav class="navbar navbar-light bg-light">
  <h1>SIMPLE AIRBNB</h1>
</nav>

<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <button class="btn btn-outline-warning" type="button"><%= link_to "Add a new flat", new_flat_path %></button>
  </form>
</nav>

<% @flats.each do |flat| %>
<div class="card-product">
  <img src="https://source.unsplash.com/100x120/?city" alt="image random">
  <div class="product_description">
    <h2><%= link_to flat.name, flat_path(id: flat.id)%></h2>
    <p><%= flat.description %></p>
  </div>
</div>
<% end %>
<%= link_to "+ Add a new flat", new_flat_path %>

app/views/flats/new.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<img src="https://source.unsplash.com/900x250/?city" alt="image ville">

<h2><%= @flat.name %></h2>
<p><strong><%= @flat.address %></strong> </p>
<p><%= @flat.description %></p>
<p><%= @flat.price_per_night %>€/Nuit <em>TTC</em></p>
<p><%= @flat.number_of_guests %> personnes maximum</p>


<button class="btn btn-outline-danger" type="button"><%= link_to "Delete", flat_path(@flat),
      method: :delete,
      data: { confirm: "Are you sure?", class: "alert" } %></button>
<button class="btn btn-outline-info" type="button"><%= link_to "back to list", flats_path %></button>
<button class="btn btn-outline-success" type="button">
<%= link_to "edit flat", edit_flat_path(@flat) %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="container col-8">
    <%= yield %>
  </div>
</html>